[package]
name = "rust-axum-sqrs-template"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.89"
axum = "0.8.6"
http-body-util = "0.1.3"
tokio = { version = "1.48.0", features = ["full"] }
tower = "0.5.2"
